<?xml version="1.0"?>
<?xml-model
  href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">

  <name>smart_car_description</name>

  <version>0.0.1</version>

  <description>
    Description and simulation package for the M3 Ackermann smart car.
  </description>

  <maintainer email="leilei_8@foxmail.com">
    adtyuhd
  </maintainer>

  <license>MIT</license>

  <buildtool_depend>
    ament_cmake
  </buildtool_depend>

  <exec_depend>
    ament_index_python
  </exec_depend>

  <exec_depend>
    xacro
  </exec_depend>

  <exec_depend>
    robot_state_publisher
  </exec_depend>

  <exec_depend>
    launch
  </exec_depend>

  <exec_depend>
    launch_ros
  </exec_depend>

  <exec_depend>
    gazebo_ros
  </exec_depend>

  <exec_depend>
    gazebo_ros2_control
  </exec_depend>

  <exec_depend>
    controller_manager
  </exec_depend>

  <exec_depend>
    joint_state_broadcaster
  </exec_depend>

  <exec_depend>
    ackermann_steering_controller
  </exec_depend>

  <export>
    <build_type>
      ament_cmake
    </build_type>
  </export>

</package>